server:
  port: 8078
  servlet:
    context-path: /autodial
---
# database
spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      jdbc-url: jdbc:log4jdbc:mariadb://192.168.102.49:3306/autocall?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true
#      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/autocall?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true
      jdbc-url: jdbc:log4jdbc:mariadb://192.168.102.115:3306/autocall?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true
      username: vdc
      password: vdc7200#
      max-lifetime: 580000
---
# devtools
spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
---
#thymeleaf
spring:
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false
---
#Log
logging:
  config:
    level: INFO
    path: ./opt/tomcat/latest/logs #/logs
    file: default
    err-file: default_error


